// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_achievement_5 = "CgkI_Pul8I8ZEAIQBA"; // <GPGSID>
        public const string leaderboard_endless_day_1 = "CgkI_Pul8I8ZEAIQBQ"; // <GPGSID>
        public const string leaderboard_endless_day_2 = "CgkI_Pul8I8ZEAIQBg"; // <GPGSID>
        public const string leaderboard_endless_day_3 = "CgkI_Pul8I8ZEAIQBw"; // <GPGSID>
        public const string achievement_achievement_1 = "CgkI_Pul8I8ZEAIQAA"; // <GPGSID>
        public const string achievement_achievement_2 = "CgkI_Pul8I8ZEAIQAQ"; // <GPGSID>
        public const string achievement_achievement_3 = "CgkI_Pul8I8ZEAIQAg"; // <GPGSID>
        public const string achievement_achievement_4 = "CgkI_Pul8I8ZEAIQAw"; // <GPGSID>

}

